import { describe, it, expect } from 'vitest'
import { writeFileSync, mkdtempSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { parseClaudeSession } from './claude.js'

function writeTmpSession(lines: Record<string, unknown>[]): string {
  const dir = mkdtempSync(join(tmpdir(), 'spool-test-'))
  const fp = join(dir, 'session.jsonl')
  writeFileSync(fp, lines.map(l => JSON.stringify(l)).join('\n'))
  return fp
}

const baseRecord = (overrides: Record<string, unknown>) => ({
  sessionId: 'test-uuid',
  cwd: '/tmp',
  timestamp: '2026-01-01T00:00:00Z',
  ...overrides,
})

describe('parseClaudeSession', () => {
  it('uses first user message as title by default', () => {
    const fp = writeTmpSession([
      baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'Help me fix the login bug' } }),
      baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: 'Sure', model: 'claude-opus-4-6' } }),
    ])
    const result = parseClaudeSession(fp)
    expect(result?.title).toBe('Help me fix the login bug')
  })

  it('uses custom-title when present', () => {
    const fp = writeTmpSession([
      baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'Help me fix the login bug' } }),
      baseRecord({ type: 'custom-title', customTitle: 'login-bugfix' }),
      baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: 'Sure', model: 'claude-opus-4-6' } }),
    ])
    const result = parseClaudeSession(fp)
    expect(result?.title).toBe('login-bugfix')
  })

  it('uses last custom-title when renamed multiple times', () => {
    const fp = writeTmpSession([
      baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'Help me' } }),
      baseRecord({ type: 'custom-title', customTitle: 'first-name' }),
      baseRecord({ type: 'custom-title', customTitle: 'final-name' }),
      baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: 'Ok', model: 'claude-opus-4-6' } }),
    ])
    const result = parseClaudeSession(fp)
    expect(result?.title).toBe('final-name')
  })

  it('skips noise from local-command-caveat / command-name / command-args slash invocations and uses real query as title', () => {
    // Reproduces the exact head of an agent-search JSONL: Claude Code injects
    // a caveat block, then a /model slash-command (with command-args="default"),
    // before the actual user prompt. Without the strip rules the title was
    // "Caveat: The messages below..." (200 chars) and a stray "default" leaked
    // into the FTS index.
    const fp = writeTmpSession([
      baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>' } }),
      baseRecord({ type: 'user', uuid: 'u2', message: { role: 'user', content: '<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args>default</command-args>' } }),
      baseRecord({ type: 'user', uuid: 'u3', message: { role: 'user', content: '<local-command-stdout>Set model to claude-opus-4-7</local-command-stdout>' } }),
      baseRecord({ type: 'user', uuid: 'u4', message: { role: 'user', content: 'what did I do today?' } }),
      baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: 'You did things.', model: 'claude-opus-4-6' } }),
    ])
    const result = parseClaudeSession(fp)
    expect(result?.title).toBe('what did I do today?')
    if (result?.kind === 'parsed') {
      const userTexts = result.session.messages.filter(m => m.role === 'user').map(m => m.contentText)
      expect(userTexts).toEqual(['what did I do today?'])
    }
  })

  it('preserves bare <command-args> content when not part of a slash-command triplet', () => {
    // If a user pastes log/code containing <command-args> outside the slash-
    // command triplet, the inner content must survive. Only the triplet form
    // (starting with <command-name>) gets stripped wholesale.
    const fp = writeTmpSession([
      baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'I saw <command-args>weird-payload</command-args> in the logs, what does it mean?' } }),
      baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: 'It means...', model: 'claude-opus-4-6' } }),
    ])
    const result = parseClaudeSession(fp)
    expect(result?.title).toBe('I saw weird-payload in the logs, what does it mean?')
  })

  it('strips spool-system-prelude marker from user message and uses what follows as title', () => {
    // Reproduces what acp.ts buildPrompt sends: a prelude block wrapping the
    // system instructions, with the user's bare query at the end.
    const fp = writeTmpSession([
      baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: '<spool-system-prelude>\nYou have access to a local knowledge base...\nlong system body\n</spool-system-prelude>\n\nwhat did I do today?' } }),
      baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: 'You did things.', model: 'claude-opus-4-6' } }),
    ])
    const result = parseClaudeSession(fp)
    expect(result?.title).toBe('what did I do today?')
  })
})
