import type Database from 'better-sqlite3'
import type { SessionSource } from '../types.js'
import { getOrCreateAskProject } from '../db/queries.js'

/**
 * One-time data migration: rewrites historical agent-search sessions that
 * were indexed before PR #150-#153 landed.
 *
 * Background:
 *   Pre-#151 agent search relied on the next sync to pick up the JSONL the
 *   downstream agent (Claude / Codex) wrote on its own. The JSONL was full
 *   of noise (Claude Code's <local-command-caveat>, /model default slash
 *   command, Spool's own giant system prompt) and landed in whatever folder
 *   Electron's process.cwd() pointed at — usually "/" in prod, packages/app
 *   in dev. Result: every old agent-search session sits under a synthetic
 *   project named "(root)" or similar, with a derived title that's just
 *   "Caveat: The messages below..." or "You have access to a local
 *   knowledge base...".
 *
 *   This migration finds those sessions by title prefix, extracts the user's
 *   real query out of the long Spool-system-prompt blob (or just uses the
 *   first non-noise user message for very early smoke-test sessions),
 *   rewrites title + title_source='spool', and moves the session to the
 *   per-source "Asks" virtual project. Empty old projects are then deleted.
 */

const CAVEAT_TITLE_PREFIX = 'Caveat: The messages below were generated by the user while running local commands'
const SPOOL_PROMPT_TITLE_PREFIX = 'You have access to a local knowledge base called Spool'
const SPOOL_PROMPT_BODY_MARKER = 'You have access to a local knowledge base called Spool'

// Noise message patterns left over from old-parser sync. These were the
// inner text of <local-command-caveat>, <command-args>, <local-command-stdout>
// tags before PR #153 added the strip rules.
const NOISE_PATTERNS: RegExp[] = [
  /^Caveat: The messages below were generated by the user while running local commands/i,
  /^default$/,
  /^Set model to /i,
  /^The user opened/i,
]

const USER_QUERY_RE = /User query:\s*"([\s\S]+?)"\s*$/

export interface Candidate {
  sessionId: number
  sessionUuid: string
  source: SessionSource
  sourceId: number
  currentProjectId: number
  currentTitle: string
  extractedQuery: string | null
}

export interface MigrationPlan {
  candidates: Candidate[]
  /** projectId → number of candidate sessions currently in it */
  affectedProjects: Map<number, number>
}

export interface MigrationResult {
  sessionsTouched: number
  sessionsTitleUpdated: number
  sessionsExtractionFailed: number
  projectsDeleted: number[]
}

// cwds that only Spool's agent search ever sets. process.cwd() of Electron
// resolves to "/" in prod; "/Users/.../packages/app" in dev. PR #151 switched
// to the dedicated path, briefly under .../agent-sessions/ before being
// renamed to .../agent-search-sessions/ later in the same PR.
const SPOOL_AGENT_CWD_PATTERNS = [
  '/',
  '%/.spool/agent-sessions',
  '%/.spool/agent-search-sessions',
  '%/spool/packages/app',
  '%/spool/.worktrees/%/packages/app',
  '%/spool-pr-identity/packages/app',
]

export function computeMigrationPlan(db: Database.Database): MigrationPlan {
  // A row is a candidate only when BOTH:
  //   (a) the title is one of the noise prefixes Spool's agent search
  //       produced before #150-#153 (cheap title-based filter), AND
  //   (b) it has at least one of two Spool-only signals — a user message
  //       containing the buildPrompt blob, OR a cwd matching one of the
  //       paths Spool used as the agent-search working directory.
  // (b) is what guards real coding sessions whose first message happened to
  // be Claude Code's injected <local-command-caveat> from being swept up.
  const cwdLikeClauses = SPOOL_AGENT_CWD_PATTERNS.map(() => 'cwd LIKE ?').join(' OR ')
  const rows = db.prepare(`
    SELECT s.id, s.session_uuid, s.source_id, s.project_id, s.title,
           src.name AS source_name
    FROM sessions s
    JOIN sources src ON src.id = s.source_id
    WHERE s.title_source = 'derived'
      AND (s.title LIKE ? OR s.title LIKE ?)
      AND (
        EXISTS (
          SELECT 1 FROM messages m
          WHERE m.session_id = s.id
            AND m.role = 'user'
            AND m.content_text LIKE ?
        )
        OR ${cwdLikeClauses}
      )
  `).all(
    `${CAVEAT_TITLE_PREFIX}%`,
    `${SPOOL_PROMPT_TITLE_PREFIX}%`,
    `%${SPOOL_PROMPT_BODY_MARKER}%`,
    ...SPOOL_AGENT_CWD_PATTERNS,
  ) as Array<{
    id: number
    session_uuid: string
    source_id: number
    project_id: number
    title: string
    source_name: SessionSource
  }>

  const candidates: Candidate[] = rows.map(r => ({
    sessionId: r.id,
    sessionUuid: r.session_uuid,
    source: r.source_name,
    sourceId: r.source_id,
    currentProjectId: r.project_id,
    currentTitle: r.title,
    extractedQuery: extractQueryForSession(db, r.id),
  }))

  const affectedProjects = new Map<number, number>()
  for (const c of candidates) {
    affectedProjects.set(c.currentProjectId, (affectedProjects.get(c.currentProjectId) ?? 0) + 1)
  }

  return { candidates, affectedProjects }
}

/**
 * Find the user's real query inside a candidate session's stored messages.
 * Walks user messages in seq order, skips known-noise rows, and returns:
 *   - the substring captured by `User query: "(.+)"` if the message is the
 *     Spool buildPrompt blob, or
 *   - the message itself, trimmed and capped at 120 chars, otherwise.
 * Returns null when no usable user message exists (extreme corruption case).
 */
export function extractQueryForSession(db: Database.Database, sessionId: number): string | null {
  const messages = db.prepare(`
    SELECT content_text FROM messages
    WHERE session_id = ? AND role = 'user'
    ORDER BY seq
  `).all(sessionId) as Array<{ content_text: string }>

  for (const m of messages) {
    const text = m.content_text.trim()
    if (!text) continue
    if (NOISE_PATTERNS.some(re => re.test(text))) continue

    if (text.includes(SPOOL_PROMPT_BODY_MARKER)) {
      const match = USER_QUERY_RE.exec(text)
      if (match?.[1]) {
        const q = match[1].trim()
        return q.length > 0 ? truncateForTitle(q) : null
      }
      // Spool prompt blob present but query couldn't be extracted; fall
      // through to next message (defensive — shouldn't normally happen).
      continue
    }

    return truncateForTitle(text)
  }
  return null
}

function truncateForTitle(s: string): string {
  const cleaned = s.replace(/\s+/g, ' ').trim()
  return cleaned.length > 120 ? cleaned.slice(0, 117) + '...' : cleaned
}

export function applyMigration(db: Database.Database, plan: MigrationPlan): MigrationResult {
  let sessionsTouched = 0
  let sessionsTitleUpdated = 0
  let sessionsExtractionFailed = 0

  // Pre-create per-source Asks projects so the loop is simple.
  const askProjectId = new Map<SessionSource, number>()
  for (const c of plan.candidates) {
    if (!askProjectId.has(c.source)) {
      askProjectId.set(c.source, getOrCreateAskProject(db, c.source))
    }
  }

  const updateWithTitle = db.prepare(`
    UPDATE sessions
    SET title = ?, title_source = 'spool', project_id = ?
    WHERE id = ?
  `)
  const updateProjectOnly = db.prepare(`
    UPDATE sessions
    SET project_id = ?, title_source = 'spool'
    WHERE id = ?
  `)

  for (const c of plan.candidates) {
    const targetProjectId = askProjectId.get(c.source)
    if (targetProjectId === undefined) continue
    sessionsTouched += 1
    if (c.extractedQuery) {
      updateWithTitle.run(c.extractedQuery, targetProjectId, c.sessionId)
      sessionsTitleUpdated += 1
    } else {
      // Couldn't extract query — keep the (noisy) title rather than blank
      // it out, but still move the row out of the wrong project and lock
      // title_source so future sync doesn't keep re-applying the noise.
      updateProjectOnly.run(targetProjectId, c.sessionId)
      sessionsExtractionFailed += 1
    }
  }

  // Delete old projects that became empty as a result.
  const projectsDeleted: number[] = []
  const countSessions = db.prepare(`SELECT COUNT(*) AS c FROM sessions WHERE project_id = ?`)
  const deleteProject = db.prepare(`DELETE FROM projects WHERE id = ?`)
  for (const projectId of plan.affectedProjects.keys()) {
    const remaining = (countSessions.get(projectId) as { c: number }).c
    if (remaining === 0) {
      deleteProject.run(projectId)
      projectsDeleted.push(projectId)
    }
  }

  return {
    sessionsTouched,
    sessionsTitleUpdated,
    sessionsExtractionFailed,
    projectsDeleted,
  }
}

export function formatPlanReport(plan: MigrationPlan, projectLabels: Map<number, string>): string {
  const lines: string[] = []
  lines.push(`Found ${plan.candidates.length} candidate session(s) across ${plan.affectedProjects.size} project(s).`)
  lines.push('')
  for (const [pid, count] of plan.affectedProjects.entries()) {
    const label = projectLabels.get(pid) ?? `<id ${pid}>`
    lines.push(`  Project ${pid} (${label}): ${count} session(s) will be moved to the Asks project for their source.`)
  }
  lines.push('')
  const failed = plan.candidates.filter(c => c.extractedQuery === null)
  lines.push(`Title extraction: ${plan.candidates.length - failed.length} succeeded, ${failed.length} failed.`)
  if (failed.length > 0) {
    lines.push('Failed extractions (will keep current noisy title; only project + title_source change):')
    for (const c of failed.slice(0, 10)) {
      lines.push(`  session ${c.sessionId} (${c.source}): "${c.currentTitle.slice(0, 60)}..."`)
    }
    if (failed.length > 10) lines.push(`  ... and ${failed.length - 10} more`)
  }
  return lines.join('\n')
}

export function getProjectLabels(db: Database.Database, projectIds: Iterable<number>): Map<number, string> {
  const labels = new Map<number, string>()
  const stmt = db.prepare(`SELECT id, display_path FROM projects WHERE id = ?`)
  for (const id of projectIds) {
    const row = stmt.get(id) as { id: number; display_path: string } | undefined
    if (row) labels.set(id, row.display_path)
  }
  return labels
}
