import { beforeEach, describe, expect, it } from 'vitest'
import Database from 'better-sqlite3'
import { runMigrations } from '../db/db.js'
import { getOrCreateProject } from '../db/queries.js'
import {
  applyMigration,
  computeMigrationPlan,
  extractQueryForSession,
} from './agent-search-cleanup.js'

let db: Database.Database

beforeEach(() => {
  db = new Database(':memory:')
  runMigrations(db)
})

function seedProject(slug: string, displayPath: string, displayName: string): number {
  return getOrCreateProject(db, 1, slug, displayPath, displayName, {
    identityKind: 'path', identityKey: displayPath,
  })
}

function seedSession(opts: {
  projectId: number
  uuid: string
  title: string
  titleSource?: 'derived' | 'spool' | 'user'
  cwd?: string
}): number {
  const result = db.prepare(`
    INSERT INTO sessions (project_id, source_id, session_uuid, file_path, title, title_source, started_at, ended_at, message_count, has_tool_use, cwd, model, raw_file_mtime)
    VALUES (?, 1, ?, ?, ?, ?, '2026-01-01', '2026-01-01', 1, 0, ?, '', '')
  `).run(opts.projectId, opts.uuid, `/fake/${opts.uuid}.jsonl`, opts.title, opts.titleSource ?? 'derived', opts.cwd ?? '/')
  return Number(result.lastInsertRowid)
}

function seedMessages(sessionId: number, msgs: Array<{ role: 'user' | 'assistant'; text: string }>): void {
  const stmt = db.prepare(`
    INSERT INTO messages (session_id, source_id, role, content_text, timestamp, seq)
    VALUES (?, 1, ?, ?, '2026-01-01', ?)
  `)
  msgs.forEach((m, i) => stmt.run(sessionId, m.role, m.text, i))
}

describe('extractQueryForSession', () => {
  it('extracts the User query from a Spool buildPrompt blob', () => {
    const pid = seedProject('p', '/', 'p')
    const sid = seedSession({ projectId: pid, uuid: 'u1', title: 'Caveat: ...' })
    seedMessages(sid, [
      { role: 'user', text: 'Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.' },
      { role: 'user', text: 'default' },
      { role: 'user', text: 'You have access to a local knowledge base called Spool that indexes the user\'s AI coding sessions.\n... lots of system prompt ...\nUser query: "what did I do yesterday?"' },
    ])
    expect(extractQueryForSession(db, sid)).toBe('what did I do yesterday?')
  })

  it('extracts a multi-line / unicode query', () => {
    const pid = seedProject('p', '/', 'p')
    const sid = seedSession({ projectId: pid, uuid: 'u1', title: 'You have...' })
    seedMessages(sid, [
      { role: 'user', text: 'You have access to a local knowledge base called Spool ... blah blah ...\nUser query: "帮我回忆一下 4 月 3 号那天我在干什么"' },
    ])
    expect(extractQueryForSession(db, sid)).toBe('帮我回忆一下 4 月 3 号那天我在干什么')
  })

  it('falls back to the first non-noise user message for early smoke-test sessions (no Spool blob)', () => {
    // Pre-buildPrompt sessions where someone ran `claude` with cwd=/ and a
    // bare query. Has caveat noise but no Spool system prompt blob.
    const pid = seedProject('p', '/', 'p')
    const sid = seedSession({ projectId: pid, uuid: 'u1', title: 'Caveat: ...' })
    seedMessages(sid, [
      { role: 'user', text: 'Caveat: The messages below were generated by the user while running local commands.' },
      { role: 'user', text: 'default' },
      { role: 'user', text: 'say hi' },
    ])
    expect(extractQueryForSession(db, sid)).toBe('say hi')
  })

  it('truncates very long extracted queries to 120 chars', () => {
    const pid = seedProject('p', '/', 'p')
    const sid = seedSession({ projectId: pid, uuid: 'u1', title: 't' })
    const longQuery = 'a'.repeat(200)
    seedMessages(sid, [
      { role: 'user', text: `You have access to a local knowledge base called Spool ...\nUser query: "${longQuery}"` },
    ])
    const result = extractQueryForSession(db, sid)
    expect(result?.length).toBe(120)
    expect(result?.endsWith('...')).toBe(true)
  })

  it('returns null when no usable user message exists', () => {
    const pid = seedProject('p', '/', 'p')
    const sid = seedSession({ projectId: pid, uuid: 'u1', title: 't' })
    seedMessages(sid, [
      { role: 'user', text: 'Caveat: The messages below were generated by the user while running local commands.' },
      { role: 'user', text: 'default' },
      { role: 'assistant', text: 'I responded.' },
    ])
    expect(extractQueryForSession(db, sid)).toBeNull()
  })
})

describe('computeMigrationPlan', () => {
  it('finds candidates by title prefix, only when title_source is derived', () => {
    const pid = seedProject('p', '/', 'p')
    const candidate = seedSession({ projectId: pid, uuid: 'u1', title: 'Caveat: The messages below were generated by the user while running local commands. ...' })
    seedSession({ projectId: pid, uuid: 'u2', title: 'a real session' })  // not a candidate
    const alreadyMigrated = seedSession({ projectId: pid, uuid: 'u3', title: 'Caveat: The messages below were generated by the user while running local commands. ...', titleSource: 'spool' })

    const plan = computeMigrationPlan(db)
    const ids = plan.candidates.map(c => c.sessionId)
    expect(ids).toContain(candidate)
    expect(ids).not.toContain(alreadyMigrated)
  })

  it('does NOT match a real coding session whose first message happens to be the injected caveat', () => {
    // Real-world case: user opens Claude in /Users/chen/github/spool, runs
    // a !shell command early, Claude Code injects <local-command-caveat>
    // as the first user message. The session has 100+ real conversation
    // turns afterwards. Title-only detection would falsely sweep this up
    // and destroy the link to the real project.
    const realProject = seedProject('spool', '/Users/chen/github/spool', 'spool')
    const realSession = seedSession({
      projectId: realProject,
      uuid: 'real-1',
      title: 'Caveat: The messages below were generated by the user while running local commands. DO NOT respond...',
      cwd: '/Users/chen/github/spool',
    })
    seedMessages(realSession, [
      { role: 'user', text: 'Caveat: The messages below were generated by the user while running local commands.' },
      { role: 'user', text: 'Help me debug this issue, here is the full error trace...' },
      { role: 'assistant', text: 'I see the problem...' },
    ])

    const plan = computeMigrationPlan(db)
    expect(plan.candidates.map(c => c.sessionId)).not.toContain(realSession)
  })

  it('matches a session even without Spool blob if cwd is in the agent-search set', () => {
    // The early smoke-test sessions (id 4, 8, 12 in real DB) have no Spool
    // blob — buildPrompt didn't exist yet — but they were spawned with
    // cwd='/' which only Spool's agent search ever does.
    const synthProject = seedProject('default', '/', '(root)')
    const sid = seedSession({
      projectId: synthProject,
      uuid: 'smoke-1',
      title: 'Caveat: The messages below were generated by the user while running local commands. DO NOT respond...',
      cwd: '/',
    })
    seedMessages(sid, [
      { role: 'user', text: 'Caveat: The messages below were generated by the user while running local commands.' },
      { role: 'user', text: 'say hi' },
    ])

    const plan = computeMigrationPlan(db)
    expect(plan.candidates.map(c => c.sessionId)).toContain(sid)
  })

  it('matches both Caveat and "You have access..." title prefixes', () => {
    const pid = seedProject('p', '/', 'p')
    const a = seedSession({ projectId: pid, uuid: 'a', title: 'Caveat: The messages below were generated by the user while running local commands. blah' })
    const b = seedSession({ projectId: pid, uuid: 'b', title: 'You have access to a local knowledge base called Spool that indexes...' })
    const c = seedSession({ projectId: pid, uuid: 'c', title: 'unrelated normal title' })

    const plan = computeMigrationPlan(db)
    const ids = plan.candidates.map(x => x.sessionId).sort()
    expect(ids).toEqual([a, b].sort())
    void c
  })
})

describe('applyMigration', () => {
  it('moves sessions to per-source Asks project and updates titles', () => {
    const oldPid = seedProject('default', '/', '(root)')
    const sid = seedSession({ projectId: oldPid, uuid: 'u1', title: 'Caveat: The messages below were generated by the user while running local commands. DO NOT respond...' })
    seedMessages(sid, [
      { role: 'user', text: 'Caveat: The messages below were generated by the user while running local commands.' },
      { role: 'user', text: 'You have access to a local knowledge base called Spool ...\nUser query: "what did I do today?"' },
    ])

    const plan = computeMigrationPlan(db)
    const result = applyMigration(db, plan)

    expect(result.sessionsTitleUpdated).toBe(1)
    const row = db.prepare('SELECT title, title_source, project_id FROM sessions WHERE id = ?').get(sid) as { title: string; title_source: string; project_id: number }
    expect(row.title).toBe('what did I do today?')
    expect(row.title_source).toBe('spool')
    const askRow = db.prepare(`SELECT slug FROM projects WHERE id = ?`).get(row.project_id) as { slug: string }
    expect(askRow.slug).toBe('__spool_ask__')
  })

  it('deletes old projects that became empty after migration', () => {
    const oldPid = seedProject('default', '/', '(root)')
    const sid = seedSession({ projectId: oldPid, uuid: 'u1', title: 'Caveat: The messages below were generated by the user while running local commands. DO NOT respond...' })
    seedMessages(sid, [
      { role: 'user', text: 'You have access to a local knowledge base called Spool\nUser query: "q"' },
    ])

    const plan = computeMigrationPlan(db)
    const result = applyMigration(db, plan)

    expect(result.projectsDeleted).toContain(oldPid)
    const stillThere = db.prepare(`SELECT id FROM projects WHERE id = ?`).get(oldPid)
    expect(stillThere).toBeUndefined()
  })

  it('keeps old project intact when it still has non-candidate sessions', () => {
    const oldPid = seedProject('mixed', '/some/real/path', 'mixed')
    const candidate = seedSession({ projectId: oldPid, uuid: 'u1', title: 'Caveat: The messages below were generated by the user while running local commands. DO NOT respond...' })
    seedMessages(candidate, [
      { role: 'user', text: 'You have access to a local knowledge base called Spool\nUser query: "q"' },
    ])
    seedSession({ projectId: oldPid, uuid: 'u2', title: 'real session unrelated' })

    const plan = computeMigrationPlan(db)
    applyMigration(db, plan)

    const stillThere = db.prepare(`SELECT id FROM projects WHERE id = ?`).get(oldPid) as { id: number } | undefined
    expect(stillThere).toBeDefined()
  })

  it('is idempotent: a second run is a no-op', () => {
    const oldPid = seedProject('default', '/', '(root)')
    const sid = seedSession({ projectId: oldPid, uuid: 'u1', title: 'Caveat: The messages below were generated by the user while running local commands. DO NOT respond...' })
    seedMessages(sid, [
      { role: 'user', text: 'You have access to a local knowledge base called Spool\nUser query: "q"' },
    ])

    applyMigration(db, computeMigrationPlan(db))
    const second = applyMigration(db, computeMigrationPlan(db))
    expect(second.sessionsTouched).toBe(0)
  })

  it('moves project + locks title_source even when extraction fails (preserves old title rather than blanking it)', () => {
    const oldPid = seedProject('default', '/', '(root)')
    const sid = seedSession({ projectId: oldPid, uuid: 'u1', title: 'Caveat: The messages below were generated by the user while running local commands.' })
    seedMessages(sid, [
      { role: 'user', text: 'Caveat: The messages below were generated by the user while running local commands.' },
      // No Spool blob, no other content — extraction returns null
    ])

    const plan = computeMigrationPlan(db)
    const result = applyMigration(db, plan)

    expect(result.sessionsExtractionFailed).toBe(1)
    const row = db.prepare('SELECT title, title_source, project_id FROM sessions WHERE id = ?').get(sid) as { title: string; title_source: string; project_id: number }
    expect(row.title).toMatch(/^Caveat:/)  // unchanged
    expect(row.title_source).toBe('spool')  // locked so future sync won't clobber
    expect(row.project_id).not.toBe(oldPid)  // moved out
  })
})
