import type Database from 'better-sqlite3'
import type { SessionSource } from '../types.js'
import { getOrCreateAskProject } from '../db/queries.js'

/**
 * v9 data migration: rewrites historical agent-search sessions that were
 * indexed before #150-#153 landed.
 *
 * Pre-#151 agent search relied on the next sync to pick up the JSONL the
 * downstream agent (Claude / Codex) wrote on its own. The JSONL was full of
 * noise (Claude Code's <local-command-caveat>, /model default slash command,
 * Spool's own giant system prompt) and landed in whatever folder Electron's
 * process.cwd() pointed at — usually "/" in prod, packages/app in dev.
 * Result: every old agent-search session sits under a synthetic project
 * named "(root)" or similar, with a derived title that's just
 * "Caveat: The messages below..." or "You have access to a local
 * knowledge base...".
 *
 * This migration finds those sessions by an explicit triple-gate, extracts
 * the user's real query out of the long Spool-system-prompt blob, rewrites
 * title + title_source='spool', and moves the session to the per-source
 * "Asks" virtual project. Empty old projects are deleted.
 *
 * Runs once via the v8→v9 schema-migration step. Idempotent: a re-run sees
 * 0 candidates because all migrated rows have title_source='spool'.
 */

const CAVEAT_TITLE_PREFIX = 'Caveat: The messages below were generated by the user while running local commands'
const SPOOL_PROMPT_TITLE_PREFIX = 'You have access to a local knowledge base called Spool'
const SPOOL_PROMPT_BODY_MARKER = 'You have access to a local knowledge base called Spool'

// Noise message patterns left over from old-parser sync. These were the
// inner text of <local-command-caveat>, <command-args>, <local-command-stdout>
// tags before #153 added the strip rules.
const NOISE_PATTERNS: RegExp[] = [
  /^Caveat: The messages below were generated by the user while running local commands/i,
  /^default$/,
  /^Set model to /i,
  /^The user opened/i,
]

const USER_QUERY_RE = /User query:\s*"([\s\S]+?)"\s*$/

export interface Candidate {
  sessionId: number
  sessionUuid: string
  source: SessionSource
  sourceId: number
  currentProjectId: number
  currentTitle: string
  extractedQuery: string | null
}

export interface MigrationPlan {
  candidates: Candidate[]
  /** projectId → number of candidate sessions currently in it */
  affectedProjects: Map<number, number>
}

export interface MigrationResult {
  sessionsTouched: number
  sessionsTitleUpdated: number
  sessionsExtractionFailed: number
  projectsDeleted: number[]
}

export function computeMigrationPlan(db: Database.Database): MigrationPlan {
  // A row is a candidate only when ALL THREE hold:
  //   (a) title_source = 'derived' (not yet migrated by Spool itself)
  //   (b) the title is one of the noise prefixes pre-#153 Spool agent
  //       search produced (cheap title-based filter)
  //   (c) at least one of the session's user messages contains the Spool
  //       buildPrompt blob signature — text that no human ever types and
  //       no agent ever generates, so it uniquely identifies a session
  //       that came out of Spool's agent search pipeline.
  //
  // (c) is what guards real coding sessions whose first message happened
  // to be Claude Code's injected <local-command-caveat>. An earlier draft
  // also accepted "cwd is in a Spool-specific path" as an alternative to
  // (c), but those paths were either too narrow (only my dev environment)
  // or too broad (cwd='/' could be anyone running claude from the
  // filesystem root). The blob check is the only signal that's both
  // Spool-unique and cross-environment robust.
  const rows = db.prepare(`
    SELECT s.id, s.session_uuid, s.source_id, s.project_id, s.title,
           src.name AS source_name
    FROM sessions s
    JOIN sources src ON src.id = s.source_id
    WHERE s.title_source = 'derived'
      AND (s.title LIKE ? OR s.title LIKE ?)
      AND EXISTS (
        SELECT 1 FROM messages m
        WHERE m.session_id = s.id
          AND m.role = 'user'
          AND m.content_text LIKE ?
      )
  `).all(
    `${CAVEAT_TITLE_PREFIX}%`,
    `${SPOOL_PROMPT_TITLE_PREFIX}%`,
    `%${SPOOL_PROMPT_BODY_MARKER}%`,
  ) as Array<{
    id: number
    session_uuid: string
    source_id: number
    project_id: number
    title: string
    source_name: SessionSource
  }>

  const candidates: Candidate[] = rows.map(r => ({
    sessionId: r.id,
    sessionUuid: r.session_uuid,
    source: r.source_name,
    sourceId: r.source_id,
    currentProjectId: r.project_id,
    currentTitle: r.title,
    extractedQuery: extractQueryForSession(db, r.id),
  }))

  const affectedProjects = new Map<number, number>()
  for (const c of candidates) {
    affectedProjects.set(c.currentProjectId, (affectedProjects.get(c.currentProjectId) ?? 0) + 1)
  }

  return { candidates, affectedProjects }
}

/**
 * Find the user's real query inside a candidate session's stored messages.
 * Walks user messages in seq order, skips known-noise rows, and returns:
 *   - the substring captured by `User query: "(.+)"` if the message is the
 *     Spool buildPrompt blob, or
 *   - the message itself, trimmed and capped at 120 chars, otherwise.
 * Returns null when no usable user message exists (extreme corruption case).
 */
export function extractQueryForSession(db: Database.Database, sessionId: number): string | null {
  const messages = db.prepare(`
    SELECT content_text FROM messages
    WHERE session_id = ? AND role = 'user'
    ORDER BY seq
  `).all(sessionId) as Array<{ content_text: string }>

  for (const m of messages) {
    const text = m.content_text.trim()
    if (!text) continue
    if (NOISE_PATTERNS.some(re => re.test(text))) continue

    if (text.includes(SPOOL_PROMPT_BODY_MARKER)) {
      const match = USER_QUERY_RE.exec(text)
      if (match?.[1]) {
        const q = match[1].trim()
        return q.length > 0 ? truncateForTitle(q) : null
      }
      // Spool prompt blob present but query couldn't be extracted; fall
      // through to next message (defensive — shouldn't normally happen).
      continue
    }

    return truncateForTitle(text)
  }
  return null
}

function truncateForTitle(s: string): string {
  const cleaned = s.replace(/\s+/g, ' ').trim()
  return cleaned.length > 120 ? cleaned.slice(0, 117) + '...' : cleaned
}

export function applyMigration(db: Database.Database, plan: MigrationPlan): MigrationResult {
  let sessionsTouched = 0
  let sessionsTitleUpdated = 0
  let sessionsExtractionFailed = 0

  // Pre-create per-source Asks projects so the loop is simple.
  const askProjectId = new Map<SessionSource, number>()
  for (const c of plan.candidates) {
    if (!askProjectId.has(c.source)) {
      askProjectId.set(c.source, getOrCreateAskProject(db, c.source))
    }
  }

  const updateWithTitle = db.prepare(`
    UPDATE sessions
    SET title = ?, title_source = 'spool', project_id = ?
    WHERE id = ?
  `)
  const updateProjectOnly = db.prepare(`
    UPDATE sessions
    SET project_id = ?, title_source = 'spool'
    WHERE id = ?
  `)

  for (const c of plan.candidates) {
    const targetProjectId = askProjectId.get(c.source)
    if (targetProjectId === undefined) continue
    sessionsTouched += 1
    if (c.extractedQuery) {
      updateWithTitle.run(c.extractedQuery, targetProjectId, c.sessionId)
      sessionsTitleUpdated += 1
    } else {
      // Couldn't extract query — keep the (noisy) title rather than blank
      // it out, but still move the row out of the wrong project and lock
      // title_source so future sync doesn't keep re-applying the noise.
      updateProjectOnly.run(targetProjectId, c.sessionId)
      sessionsExtractionFailed += 1
    }
  }

  // Delete old projects that became empty as a result.
  const projectsDeleted: number[] = []
  const countSessions = db.prepare(`SELECT COUNT(*) AS c FROM sessions WHERE project_id = ?`)
  const deleteProject = db.prepare(`DELETE FROM projects WHERE id = ?`)
  for (const projectId of plan.affectedProjects.keys()) {
    const remaining = (countSessions.get(projectId) as { c: number }).c
    if (remaining === 0) {
      deleteProject.run(projectId)
      projectsDeleted.push(projectId)
    }
  }

  return {
    sessionsTouched,
    sessionsTitleUpdated,
    sessionsExtractionFailed,
    projectsDeleted,
  }
}

/** Convenience entry point used by the v9 schema migration. */
export function runAgentSearchCleanup(db: Database.Database): MigrationResult {
  const plan = computeMigrationPlan(db)
  return applyMigration(db, plan)
}
