import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { mkdtempSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import Database from 'better-sqlite3'
import { runMigrations } from '../db/db.js'
import { getOrCreateProject } from '../db/queries.js'
import {
  applyMigration,
  computeMigrationPlan,
  extractQueryForSession,
} from './agent-search-cleanup.js'

let db: Database.Database

beforeEach(() => {
  db = new Database(':memory:')
  runMigrations(db)
})

function seedProject(slug: string, displayPath: string, displayName: string): number {
  return getOrCreateProject(db, 1, slug, displayPath, displayName, {
    identityKind: 'path', identityKey: displayPath,
  })
}

function seedSession(opts: {
  projectId: number
  uuid: string
  title: string
  titleSource?: 'derived' | 'spool' | 'user'
  cwd?: string
}): number {
  const result = db.prepare(`
    INSERT INTO sessions (project_id, source_id, session_uuid, file_path, title, title_source, started_at, ended_at, message_count, has_tool_use, cwd, model, raw_file_mtime)
    VALUES (?, 1, ?, ?, ?, ?, '2026-01-01', '2026-01-01', 1, 0, ?, '', '')
  `).run(opts.projectId, opts.uuid, `/fake/${opts.uuid}.jsonl`, opts.title, opts.titleSource ?? 'derived', opts.cwd ?? '/')
  return Number(result.lastInsertRowid)
}

function seedMessages(sessionId: number, msgs: Array<{ role: 'user' | 'assistant'; text: string }>): void {
  const stmt = db.prepare(`
    INSERT INTO messages (session_id, source_id, role, content_text, timestamp, seq)
    VALUES (?, 1, ?, ?, '2026-01-01', ?)
  `)
  msgs.forEach((m, i) => stmt.run(sessionId, m.role, m.text, i))
}

const NOISE_TITLE = 'Caveat: The messages below were generated by the user while running local commands. DO NOT respond...'
const SPOOL_BLOB = (q: string) => `You have access to a local knowledge base called Spool that indexes the user\'s AI coding sessions.\n... lots of system prompt ...\nUser query: "${q}"`

describe('extractQueryForSession', () => {
  it('extracts the User query from a Spool buildPrompt blob', () => {
    const pid = seedProject('p', '/', 'p')
    const sid = seedSession({ projectId: pid, uuid: 'u1', title: NOISE_TITLE })
    seedMessages(sid, [
      { role: 'user', text: 'Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.' },
      { role: 'user', text: 'default' },
      { role: 'user', text: SPOOL_BLOB('what did I do yesterday?') },
    ])
    expect(extractQueryForSession(db, sid)).toBe('what did I do yesterday?')
  })

  it('extracts a multi-line / unicode query', () => {
    const pid = seedProject('p', '/', 'p')
    const sid = seedSession({ projectId: pid, uuid: 'u1', title: NOISE_TITLE })
    seedMessages(sid, [
      { role: 'user', text: SPOOL_BLOB('帮我回忆一下 4 月 3 号那天我在干什么') },
    ])
    expect(extractQueryForSession(db, sid)).toBe('帮我回忆一下 4 月 3 号那天我在干什么')
  })

  it('truncates very long extracted queries to 120 chars', () => {
    const pid = seedProject('p', '/', 'p')
    const sid = seedSession({ projectId: pid, uuid: 'u1', title: NOISE_TITLE })
    const longQuery = 'a'.repeat(200)
    seedMessages(sid, [{ role: 'user', text: SPOOL_BLOB(longQuery) }])
    const result = extractQueryForSession(db, sid)
    expect(result?.length).toBe(120)
    expect(result?.endsWith('...')).toBe(true)
  })

  it('returns null when no usable user message exists', () => {
    const pid = seedProject('p', '/', 'p')
    const sid = seedSession({ projectId: pid, uuid: 'u1', title: NOISE_TITLE })
    seedMessages(sid, [
      { role: 'user', text: 'Caveat: The messages below were generated by the user while running local commands.' },
      { role: 'user', text: 'default' },
      { role: 'assistant', text: 'I responded.' },
    ])
    expect(extractQueryForSession(db, sid)).toBeNull()
  })
})

describe('computeMigrationPlan — detection contract', () => {
  it('matches a session with noise title + Spool blob in a user message', () => {
    const pid = seedProject('p', '/', 'p')
    const sid = seedSession({ projectId: pid, uuid: 'u1', title: NOISE_TITLE })
    seedMessages(sid, [{ role: 'user', text: SPOOL_BLOB('q') }])
    expect(computeMigrationPlan(db).candidates.map(c => c.sessionId)).toContain(sid)
  })

  it('matches both noise title prefixes (Caveat AND "You have access...")', () => {
    const pid = seedProject('p', '/', 'p')
    const a = seedSession({ projectId: pid, uuid: 'a', title: NOISE_TITLE })
    seedMessages(a, [{ role: 'user', text: SPOOL_BLOB('q1') }])
    const b = seedSession({ projectId: pid, uuid: 'b', title: 'You have access to a local knowledge base called Spool that indexes...' })
    seedMessages(b, [{ role: 'user', text: SPOOL_BLOB('q2') }])
    const ids = computeMigrationPlan(db).candidates.map(c => c.sessionId).sort()
    expect(ids).toEqual([a, b].sort())
  })

  it('does NOT match when title_source is already "spool" (re-run idempotency)', () => {
    const pid = seedProject('p', '/', 'p')
    const sid = seedSession({ projectId: pid, uuid: 'u1', title: NOISE_TITLE, titleSource: 'spool' })
    seedMessages(sid, [{ role: 'user', text: SPOOL_BLOB('q') }])
    expect(computeMigrationPlan(db).candidates).toHaveLength(0)
  })

  it('does NOT match a real coding session whose first message happens to be the injected caveat (no Spool blob)', () => {
    // Real-world false-positive risk: user opens Claude in /Users/chen/github/spool,
    // runs a !shell command early, Claude Code injects <local-command-caveat>
    // as the first user message. The session has 100+ real conversation
    // turns afterwards. This is the case the blob gate exists to reject.
    const realProject = seedProject('spool', '/Users/chen/github/spool', 'spool')
    const realSession = seedSession({
      projectId: realProject, uuid: 'real-1',
      title: NOISE_TITLE,
      cwd: '/Users/chen/github/spool',
    })
    seedMessages(realSession, [
      { role: 'user', text: 'Caveat: The messages below were generated by the user while running local commands.' },
      { role: 'user', text: 'Help me debug this issue, here is the full error trace...' },
      { role: 'assistant', text: 'I see the problem...' },
    ])
    expect(computeMigrationPlan(db).candidates).toHaveLength(0)
  })

  it('does NOT match a session without the Spool blob even when cwd is suspicious (e.g. cwd=/)', () => {
    // Pre-buildPrompt smoke-test sessions had cwd='/' and a caveat title
    // but no blob. Earlier drafts used cwd as a fallback signal; the final
    // gate is blob-only. Trade-off: a handful of ancient dev experiments
    // stay in their old project. Worth it — a false positive on real work
    // is far worse than a false negative on a smoke test.
    const synthProject = seedProject('default', '/', '(root)')
    const sid = seedSession({
      projectId: synthProject, uuid: 'smoke-1',
      title: NOISE_TITLE, cwd: '/',
    })
    seedMessages(sid, [
      { role: 'user', text: 'Caveat: The messages below were generated by the user while running local commands.' },
      { role: 'user', text: 'say hi' },
    ])
    expect(computeMigrationPlan(db).candidates).toHaveLength(0)
  })

  it('does NOT match a session with Spool blob but unrelated title (defensive: title gate is required too)', () => {
    const pid = seedProject('p', '/', 'p')
    const sid = seedSession({ projectId: pid, uuid: 'u1', title: 'an actual real session title' })
    seedMessages(sid, [{ role: 'user', text: SPOOL_BLOB('q') }])
    expect(computeMigrationPlan(db).candidates).toHaveLength(0)
  })
})

describe('applyMigration', () => {
  it('moves sessions to per-source Asks project, sets extracted title and locks title_source', () => {
    const oldPid = seedProject('default', '/', '(root)')
    const sid = seedSession({ projectId: oldPid, uuid: 'u1', title: NOISE_TITLE })
    seedMessages(sid, [{ role: 'user', text: SPOOL_BLOB('what did I do today?') }])

    applyMigration(db, computeMigrationPlan(db))

    const row = db.prepare('SELECT title, title_source, project_id FROM sessions WHERE id = ?').get(sid) as { title: string; title_source: string; project_id: number }
    expect(row.title).toBe('what did I do today?')
    expect(row.title_source).toBe('spool')
    const askRow = db.prepare(`SELECT slug FROM projects WHERE id = ?`).get(row.project_id) as { slug: string }
    expect(askRow.slug).toBe('__spool_ask__')
  })

  it('deletes old projects that became empty after migration', () => {
    const oldPid = seedProject('default', '/', '(root)')
    const sid = seedSession({ projectId: oldPid, uuid: 'u1', title: NOISE_TITLE })
    seedMessages(sid, [{ role: 'user', text: SPOOL_BLOB('q') }])

    const result = applyMigration(db, computeMigrationPlan(db))
    expect(result.projectsDeleted).toContain(oldPid)
    expect(db.prepare(`SELECT id FROM projects WHERE id = ?`).get(oldPid)).toBeUndefined()
  })

  it('keeps old project intact when it still has non-candidate sessions', () => {
    const oldPid = seedProject('mixed', '/some/real/path', 'mixed')
    const candidate = seedSession({ projectId: oldPid, uuid: 'u1', title: NOISE_TITLE })
    seedMessages(candidate, [{ role: 'user', text: SPOOL_BLOB('q') }])
    seedSession({ projectId: oldPid, uuid: 'u2', title: 'real session unrelated' })

    applyMigration(db, computeMigrationPlan(db))
    expect(db.prepare(`SELECT id FROM projects WHERE id = ?`).get(oldPid)).toBeDefined()
  })

  it('moves project + locks title_source even when query extraction fails', () => {
    // Edge case: blob is present (so the row is a candidate) but the
    // `User query: "..."` line is absent (very early/malformed prompt).
    const oldPid = seedProject('default', '/', '(root)')
    const sid = seedSession({ projectId: oldPid, uuid: 'u1', title: NOISE_TITLE })
    seedMessages(sid, [
      { role: 'user', text: 'You have access to a local knowledge base called Spool that indexes... (no User query line)' },
    ])

    const result = applyMigration(db, computeMigrationPlan(db))
    expect(result.sessionsExtractionFailed).toBe(1)

    const row = db.prepare('SELECT title, title_source, project_id FROM sessions WHERE id = ?').get(sid) as { title: string; title_source: string; project_id: number }
    expect(row.title).toMatch(/^Caveat:/)            // unchanged
    expect(row.title_source).toBe('spool')           // locked
    expect(row.project_id).not.toBe(oldPid)          // moved out
  })

  it('is idempotent: a second run touches nothing', () => {
    const oldPid = seedProject('default', '/', '(root)')
    const sid = seedSession({ projectId: oldPid, uuid: 'u1', title: NOISE_TITLE })
    seedMessages(sid, [{ role: 'user', text: SPOOL_BLOB('q') }])

    applyMigration(db, computeMigrationPlan(db))
    const second = applyMigration(db, computeMigrationPlan(db))
    expect(second.sessionsTouched).toBe(0)
  })
})

// ── End-to-end via the schema migration runner ──────────────────────────
const tempDirs: string[] = []
afterEach(() => {
  vi.unstubAllEnvs()
  vi.resetModules()
  while (tempDirs.length > 0) {
    const d = tempDirs.pop()
    if (d) rmSync(d, { recursive: true, force: true })
  }
})

function makeTempDir(prefix: string): string {
  const dir = mkdtempSync(join(tmpdir(), prefix))
  tempDirs.push(dir)
  return dir
}

function seedV8(dbPath: string): void {
  const seed = new Database(dbPath)
  seed.pragma('journal_mode = WAL')
  seed.pragma('foreign_keys = ON')
  seed.exec(`
    CREATE TABLE sources (
      id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE,
      base_path TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
    INSERT INTO sources (name, base_path) VALUES
      ('claude','~/.claude/projects'),('codex','~/.codex/sessions'),('gemini','~/.gemini/tmp');

    CREATE TABLE projects (
      id INTEGER PRIMARY KEY, source_id INTEGER NOT NULL,
      slug TEXT NOT NULL, display_path TEXT NOT NULL,
      display_name TEXT NOT NULL,
      identity_kind TEXT, identity_key TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
    INSERT INTO projects (source_id, slug, display_path, display_name, identity_kind, identity_key)
      VALUES
        (1, 'default',         '/',                                  '(root)', 'path', '/'),
        (1, '-Users-real-spool', '/Users/real/spool',                'spool',  'path', '/Users/real/spool');

    CREATE TABLE sessions (
      id INTEGER PRIMARY KEY,
      project_id INTEGER NOT NULL,
      source_id INTEGER NOT NULL,
      session_uuid TEXT NOT NULL UNIQUE,
      file_path TEXT NOT NULL UNIQUE,
      title TEXT,
      title_source TEXT NOT NULL DEFAULT 'derived',
      started_at TEXT NOT NULL,
      ended_at TEXT NOT NULL,
      message_count INTEGER NOT NULL DEFAULT 0,
      has_tool_use INTEGER NOT NULL DEFAULT 0,
      cwd TEXT, model TEXT, raw_file_mtime TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
    -- Two agent-search sessions (project 1, with blob) — should be migrated
    INSERT INTO sessions (id, project_id, source_id, session_uuid, file_path, title, started_at, ended_at, message_count, raw_file_mtime)
      VALUES
        (1, 1, 1, 'ag-1', '/fake/ag-1.jsonl',
         'Caveat: The messages below were generated by the user while running local commands. DO NOT respond...',
         '2026-04-01', '2026-04-01', 3, '2026-04-01'),
        (2, 1, 1, 'ag-2', '/fake/ag-2.jsonl',
         'Caveat: The messages below were generated by the user while running local commands. DO NOT respond...',
         '2026-04-02', '2026-04-02', 3, '2026-04-02');
    -- One real coding session (project 2, caveat title but no blob) — must NOT be migrated
    INSERT INTO sessions (id, project_id, source_id, session_uuid, file_path, title, started_at, ended_at, message_count, raw_file_mtime)
      VALUES
        (3, 2, 1, 'real-1', '/fake/real-1.jsonl',
         'Caveat: The messages below were generated by the user while running local commands. DO NOT respond...',
         '2026-04-03', '2026-04-03', 80, '2026-04-03');

    CREATE TABLE messages (
      id INTEGER PRIMARY KEY,
      session_id INTEGER NOT NULL,
      source_id INTEGER NOT NULL,
      msg_uuid TEXT, parent_uuid TEXT,
      role TEXT NOT NULL,
      content_text TEXT NOT NULL DEFAULT '',
      timestamp TEXT NOT NULL,
      is_sidechain INTEGER NOT NULL DEFAULT 0,
      tool_names TEXT NOT NULL DEFAULT '[]',
      seq INTEGER NOT NULL
    );
    INSERT INTO messages (session_id, source_id, role, content_text, timestamp, seq) VALUES
      (1, 1, 'user', 'You have access to a local knowledge base called Spool ...\nUser query: "first query"', '2026-04-01', 0),
      (2, 1, 'user', 'You have access to a local knowledge base called Spool ...\nUser query: "second query"', '2026-04-02', 0),
      (3, 1, 'user', 'Caveat: The messages below were generated by the user while running local commands.', '2026-04-03', 0),
      (3, 1, 'user', 'Help me with this real bug', '2026-04-03', 1);

    CREATE TABLE pins (
      session_uuid TEXT PRIMARY KEY,
      pinned_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `)
  seed.pragma('user_version = 8')
  seed.close()
}

describe('v9 schema migration (end-to-end via runMigrations)', () => {
  it('migrates pre-#153 agent-search sessions and leaves real sessions alone', async () => {
    const spoolDir = makeTempDir('spool-v9-mig-')
    const dbPath = join(spoolDir, 'spool.db')
    seedV8(dbPath)

    vi.stubEnv('SPOOL_DATA_DIR', spoolDir)
    vi.resetModules()
    const dbModule = await import('../db/db.js')
    const liveDb = dbModule.getDB()

    expect((liveDb.pragma('user_version') as Array<{ user_version: number }>)[0]?.user_version).toBeGreaterThanOrEqual(9)

    // Two agent-search sessions migrated:
    //   - title rewritten to extracted query
    //   - title_source = 'spool'
    //   - moved to the Asks/claude virtual project
    const ag1 = liveDb.prepare(`SELECT title, title_source FROM sessions WHERE session_uuid = 'ag-1'`).get() as { title: string; title_source: string }
    const ag2 = liveDb.prepare(`SELECT title, title_source FROM sessions WHERE session_uuid = 'ag-2'`).get() as { title: string; title_source: string }
    expect(ag1.title).toBe('first query')
    expect(ag1.title_source).toBe('spool')
    expect(ag2.title).toBe('second query')
    expect(ag2.title_source).toBe('spool')

    const askProject = liveDb.prepare(`SELECT id FROM projects WHERE slug = '__spool_ask__'`).get() as { id: number }
    const ag1ProjectId = (liveDb.prepare(`SELECT project_id FROM sessions WHERE session_uuid = 'ag-1'`).get() as { project_id: number }).project_id
    expect(ag1ProjectId).toBe(askProject.id)

    // Old empty synthetic project deleted.
    expect(liveDb.prepare(`SELECT id FROM projects WHERE slug = 'default'`).get()).toBeUndefined()

    // Real session untouched: same title, same title_source, same project.
    const real = liveDb.prepare(`SELECT title, title_source, project_id FROM sessions WHERE session_uuid = 'real-1'`).get() as { title: string; title_source: string; project_id: number }
    expect(real.title).toMatch(/^Caveat:/)
    expect(real.title_source).toBe('derived')
    const realProjectStillThere = liveDb.prepare(`SELECT slug FROM projects WHERE id = ?`).get(real.project_id) as { slug: string }
    expect(realProjectStillThere.slug).toBe('-Users-real-spool')

    liveDb.close()
  })

  it('writes a backup file before running on a non-empty DB', async () => {
    const spoolDir = makeTempDir('spool-v9-backup-')
    const dbPath = join(spoolDir, 'spool.db')
    seedV8(dbPath)

    vi.stubEnv('SPOOL_DATA_DIR', spoolDir)
    vi.resetModules()
    const dbModule = await import('../db/db.js')
    dbModule.getDB().close()

    const { readdirSync } = await import('node:fs')
    const backups = readdirSync(join(spoolDir, 'backups'))
    expect(backups.some(f => f.startsWith('spool-pre-v9-'))).toBe(true)
  })

  it('is a no-op on a fresh install (no v9 candidates)', async () => {
    const spoolDir = makeTempDir('spool-v9-fresh-')
    vi.stubEnv('SPOOL_DATA_DIR', spoolDir)
    vi.resetModules()
    const dbModule = await import('../db/db.js')
    const liveDb = dbModule.getDB()

    expect((liveDb.pragma('user_version') as Array<{ user_version: number }>)[0]?.user_version).toBeGreaterThanOrEqual(9)
    expect(dbModule.wasNewDb()).toBe(true)
    liveDb.close()
  })
})
